### ISSUE TITLE
svg 이미지 사용 방식

### ISSUE THREAD

**Issue by danimkim** [team-morado/tech-info-sharing-note#18]
@mmcho122 혹시 svg 파일을 import 하는 방식이 로딩이 빠르다거나 하는 이점이 혹시 있을까요?
저는 Svg.js에 필요한 아이콘을 컴포넌트화해서 사용하는 식으로 했는데
통일하는 것이 좋을거 같아서요!
아래는 제가 사용한 방식입니다.
```
// ViewCard.js 
import ExternalLink from "./Svg";

<Link to="#">
      <a>
          <ExternalLink />
          공유페이지 새창으로 열기
      </a>
  </Link>
```

_Originally posted by @dahhnym in https://github.com/team-morado/tech-info-sharing-note/pull/16#discussion_r814500427_

**Comment by mmcho122** [comment]
@dahhnym Svg 컴포넌트 파일이 없는 버전에서 작업하느라 임의로 svg 파일을 import 시킨 것입니다!
다님님께서 말씀하신 방식으로 통일성 있게 수정하겠습니다 :)

**Comment by danimkim** [comment]
네 그럼 SVG 이미지 사용시 컴포넌트화 하여 사용하는 것으로 하겠습니다!
컴포넌트화한 svg의 색, 크기 변경하는 방법을 설명한 자료가 있어서 링크 첨부해둘게요

https://kyounghwan01.github.io/blog/React/handling-svg/#svg-%E1%84%8B%E1%85%A8%E1%84%89%E1%85%B5

**Comment by mmcho122** [comment]
네 참고하겠습니다! 감사해요 :)
