### ISSUE TITLE
#21 뷰페이지 게시글 본문 영역 height 건

### ISSUE THREAD

**Issue by danimkim** [team-morado/tech-info-sharing-note#22]
(이슈 원문 #21)

게시글 본문 영역의 height값을 `vh` 단위를 써서 유동적으로 적용되게끔 했는데 그래도 맨 아래의 수정,삭제 버튼이 잘려서 나오는 경우가 있습니다ㅠ 이런 경우는 height값을 어떻게 주어야 모바일 화면에서 버튼이 잘리지 않고 잘 나올수 있게 할수있을까요?
![image](https://user-images.githubusercontent.com/74545780/155725469-2b7e1df2-da8b-4ad8-9c0a-0e372c1e4f7d.png)

게시글 본문 영역의 css 속성은 아래와 같이 줬습니다.
```js 
const Content = styled.p`
    min-height: 100px;
    max-height: 25vh;
    overflow: scroll;
    overflow-x: hidden;
    line-height: 20px;
`
```

_Originally posted by @dahhnym in https://github.com/team-morado/tech-info-sharing-note/pull/21#discussion_r814783775_

**Comment by mmcho122** [comment]
Footer 컴포넌트에 position 속성을 fixed로 줘서 이런 현상이 나타나는 것 같습니다!
제가 맡은 부분이니 수정하겠습니다 :)

**Comment by danimkim** [comment]
header, footer를 제외한 content에 max-height값(브라우저 height - header, footer의 height)을 주는 방식으로 하기로 논의되었습니다.
