### ISSUE TITLE
리스트아이템 본문내용 표시 방식

### ISSUE THREAD

**Issue by danimkim** [team-morado/tech-info-sharing-note#30]
![image](https://user-images.githubusercontent.com/74545780/155833510-5c6b1a6b-122f-4d0a-b676-186de8bc2ca8.png)
게시글 본문 내용이 길 경우 리스트아이템에는 한두줄 정도 표시해주고 ellipsis 처리해주면 좋을 것 같습니다.

<ellipsis 처리 예시>
![image](https://user-images.githubusercontent.com/74545780/155833552-23b51562-b11d-44f8-9de0-1e36f093de61.png)

**Comment by sooonlog** [comment]
넵 말씀하신 방식으로 elipsis 처리하겠습니다! 감사합니다🙏

**Comment by danimkim** [comment]
#35 이슈에 본 이슈건에 대한 내용이 추가되어 이 이슈는 close합니다
