### ISSUE TITLE
올바르지 않은 URL형식에 따른 공유URL 새창열기 문제

### ISSUE THREAD

**Issue by danimkim** [team-morado/tech-info-sharing-note#45]
뷰페이지에서 새창열기할 때 입력된 url 주소에 `http://`가 입력되어 있지 않은 경우 url 형식에 맞지 않아 올바른 주소로 새창열기가 되지 않습니다.

![image](https://user-images.githubusercontent.com/74545780/156536433-d05a8b85-60fc-494f-ae00-05a0f2c0fc77.png)

따라서 올바른 url주소로 새창열기 이동을 위한 url 형식에 맞게 입력값을 받게끔하는 간단한 기능을 붙이려고 하는데 괜찮을지 의견구합니다.

- 글쓰기페이지에 진입했을때 공유URL 입력하는 input창에 기본적으로 `http://` 가 입력되어 있음
![image](https://user-images.githubusercontent.com/74545780/156536998-bd4e2b1e-2037-484d-9a9e-74138e4b7f72.png)

- 사용자가 `http://` 없이 사이트 주소만 입력했다면 자동적으로 앞에 `http://` 붙여서 저장되게끔 기능 구현

**Comment by Kyoo130** [comment]
@dahhnym
지난 번 2차 개발 건으로 얘기했던 내용과 동일한 건으로 저도 고려했던 내용이라 좋을 것 같습니다.

먼저, 현재 글자수 조건이 있어서 이쪽 기능도 전체적으로 개선해야 하는 상황이고,
URL 자체를 공유하지 않을 수도 있으니, URL 자체가 없을때 null 값으로 반환해 주도록
기능도 공유하면 좋을 것 같습니다.

**Comment by danimkim** [comment]
@Kyoo130 아 지난번에 언급하셨었나보군요 제가 놓쳤나봅니다 죄송해요ㅠ

현재 글자수 조건이 모든 input에 다 걸려있고 focus로만 처리되어있는데
option을 select하지 않았거나 input창에 입력안한 경우 창 아래에 문구표시하는걸로 2차 작업 하신다고 얘기해주셨던 건 기억납니다.

> 먼저, 현재 글자수 조건이 있어서 이쪽 기능도 전체적으로 개선해야 하는 상황이고, URL 자체를 공유하지 않을 수도 있으니, URL 자체가 없을때 null 값으로 반환해 주도록 기능도 공유하면 좋을 것 같습니다.

URL자체를 공유하지 않는다는 게 어떤 의미일까요?ㅠ
저는 URL을 무조건 입력하는 걸로 하고, 입력하지 않고 작성완료 눌렀을시는 focus 주고 아래에 'url 입력해주세요' 문구를 표시하는게 어떨까 생각합니다.
대신 `공유하고 싶은 이유 or 상세정보` 부분은 사용자가 아무것도 입력하고 싶지 않을 수도 있고 필수로 입력할 필요는 없다고 저는 생각해서, 아무것도 입력하지 않은 경우 그냥 `string` 빈값("") 입력해서 저장되게끔 하는건 어떨까요?

문구표시의 경우, 아래처럼 하는건 어떨까요?
- select박스 select 하지 않은 경우, 셀렉트박스 아래에 'xx를 선택해주세요' 표시
- input창의 경우 아래의 문구 input창 아래에 표시
  - 제목 : '5글자 이상 입력해주세요'
  - 공유URL : '공유할 링크를 입력해주세요'

**Comment by danimkim** [comment]
#64 
프로토콜 없이 주소만 입력한 경우 `http://`를 주소 앞에 붙여 state에 저장하는 방식으로 본 이슈를 해결하였습니다.
